;;; org-auto-scheduler-analytics.el --- Schedule adherence, retrospectives & reporting -*- lexical-binding: t; -*-

;; Copyright (C) 2024-2026 SSD2019
;; License: GPL-3.0-or-later

;;; Commentary:
;;
;; Schedule adherence scoring, weekly retrospectives, compact Gantt timeline
;; rendering, and overrun modeline warnings for org-auto-scheduler.

;;; Code:

(require 'org)
(require 'cl-lib)
(require 'org-clock)
(require 'tabulated-list)
(require 'color)

(defcustom org-auto-scheduler-overrun-mode-line-enabled t
  "When non-nil, display task overrun indicators in the mode line when clocked in."
  :type 'boolean
  :group 'org-auto-scheduler)

;;; Adherence Tracking
(defcustom org-auto-scheduler-adherence-file (expand-file-name "org-auto-scheduler-adherence.el" user-emacs-directory)
  "File to save schedule adherence snapshots and history."
  :type 'string
  :group 'org-auto-scheduler)

(defvar org-auto-scheduler--adherence-history nil
  "Alist mapping date strings (YYY-MM-DD) to daily adherence data.
Format: ((date . ((:score . 85.5) (:streak . 3) (:details . ...))))")

(defvar org-auto-scheduler--adherence-snapshots nil
  "Alist mapping date strings to the list of tasks planned for that day.
Each task is stored as a plist: (:id ID :file FILE :pos POS :heading HEADING :effort EFFORT :category CATEGORY :tags TAGS :scheduled TIME)")

(defun org-auto-scheduler-save-adherence ()
  "Save adherence data to `org-auto-scheduler-adherence-file`.
Prunes snapshots older than 30 days to prevent excessive file growth."
  (let* ((cutoff-time (time-subtract (current-time) (days-to-time 30)))
         (cutoff-date-str (format-time-string "%Y-%m-%d" cutoff-time)))
    ;; Filter out snapshots older than 30 days
    (setq org-auto-scheduler--adherence-snapshots
          (cl-remove-if (lambda (entry)
                          (string< (car entry) cutoff-date-str))
                        org-auto-scheduler--adherence-snapshots)))
  (with-temp-file org-auto-scheduler-adherence-file
    (let ((print-length nil)
          (print-level nil))
      (insert ";;; -*- lexical-binding: t; -*-\n")
      (insert ";; Auto-generated by org-auto-scheduler\n")
      (insert (format "(setq org-auto-scheduler--adherence-history '%S)\n"
                      org-auto-scheduler--adherence-history))
      (insert (format "(setq org-auto-scheduler--adherence-snapshots '%S)\n"
                      org-auto-scheduler--adherence-snapshots)))))

(defun org-auto-scheduler-load-adherence ()
  "Load adherence data from `org-auto-scheduler-adherence-file`."
  (when (file-exists-p org-auto-scheduler-adherence-file)
    (load org-auto-scheduler-adherence-file t t t)))

(add-hook 'kill-emacs-hook #'org-auto-scheduler-save-adherence)
(org-auto-scheduler-load-adherence)

;;; Schedule Adherence Tracking & Scoring

(defun org-auto-scheduler-snapshot-schedule ()
  "Record a snapshot of today's scheduled tasks for adherence tracking.
Only records tasks that have a SCHEDULED property matching today's date."
  (interactive)
  (let* ((today-date (format-time-string "%Y-%m-%d"))
         (snapshot nil)
         (count 0))
    (org-map-entries
     (lambda ()
       (let* ((scheduled-time-str (org-entry-get (point) "SCHEDULED"))
              (scheduled-time (when scheduled-time-str (org-time-string-to-time scheduled-time-str))))
         (when (and scheduled-time
                    (string= (format-time-string "%Y-%m-%d" scheduled-time) today-date)
                    (not (member "ARCHIVE" (org-get-tags))))
           (let* ((id (or (org-id-get) (org-id-get-create)))
                  (file (buffer-file-name))
                  (pos (point))
                  (heading (org-get-heading t t t t))
                  (effort (org-auto-scheduler-get-effort (point-marker)))
                  (category (org-get-category))
                  (tags (org-get-tags))
                  (task-plist (list :id id
                                    :file file
                                    :pos pos
                                    :heading heading
                                    :effort effort
                                    :category category
                                    :tags tags
                                    :scheduled scheduled-time-str)))
             (push task-plist snapshot)
             (cl-incf count)))))
     nil 'agenda)
    ;; Update snapshot list
    (let ((existing (assoc today-date org-auto-scheduler--adherence-snapshots)))
      (if existing
          (setcdr existing snapshot)
        (push (cons today-date snapshot) org-auto-scheduler--adherence-snapshots)))
    (org-auto-scheduler-save-adherence)
    (message "Snapshot saved: %d tasks planned for today." count)))

(defun org-auto-scheduler-score-schedule (&optional target-date no-display)
  "Score performance against a morning's snapshot.
If TARGET-DATE is provided or prompted for, scores that specific day.
When scoring the current day, only considers tasks whose expected
start time is in the past.
If NO-DISPLAY is non-nil, suppresses the graphical output."
  (interactive
   (list (when current-prefix-arg
           (let ((prompt-date (org-read-date nil nil nil "Score schedule for date: ")))
             (when prompt-date
               ;; org-read-date returns a date string, we need YYYY-MM-DD
               (format-time-string "%Y-%m-%d" (org-time-string-to-time prompt-date)))))))
  (let* ((score-date (or target-date (format-time-string "%Y-%m-%d")))
         (is-today (string= score-date (format-time-string "%Y-%m-%d")))
         (yesterday-date (format-time-string "%Y-%m-%d"
                                             (time-subtract (org-time-string-to-time score-date) (days-to-time 1))))
         (snapshot (cdr (assoc score-date org-auto-scheduler--adherence-snapshots)))
         (yesterday-snapshot (cdr (assoc yesterday-date org-auto-scheduler--adherence-snapshots)))
         (current-time (current-time))
         (clock-intervals (org-auto-scheduler-get-clock-intervals score-date))
         (total-effort 0.0)
         (earned-effort 0.0)
         (total-overlap-mins 0.0)
         (punctuality-earned 0.0)
         (weighted-earned 0.0)
         (weighted-total 0.0)
         (tasks-results nil)
         (cat-stats (make-hash-table :test 'equal))
         (postponed-tasks 0)
         (unplanned-tasks nil)
         (missed-tasks nil))

    (unless snapshot
      (if is-today
          (user-error "No schedule snapshot found for today! Run `M-x org-auto-scheduler-snapshot-schedule` first.")
        (user-error "No schedule snapshot found for %s." score-date)))

    ;; 1. Check Snapshot Tasks (Earned vs Total)
    (dolist (task snapshot)
      (let* ((id (plist-get task :id))
             (heading (plist-get task :heading))
             (effort (or (plist-get task :effort) 30)) ; fallback to 30 mins
             (category (or (plist-get task :category) "Uncategorized"))
             (scheduled-time (plist-get task :scheduled))
             (marker (org-id-find id t))
             (is-done nil)
             (clocked 0)
             (earned 0.0)
             (should-score t)
             (has-passed t))

        ;; Evaluate state and clocked time first
        (when marker
          (org-with-point-at marker
            (setq is-done (member (org-get-todo-state) org-done-keywords))
            (setq clocked (org-auto-scheduler-get-clocked-time marker))))

        ;; Time-gating: Only evaluate tasks whose start time has passed if scoring "today"
        (when (and is-today scheduled-time)
          (setq has-passed (time-less-p (org-time-string-to-time scheduled-time) current-time))
          (when (and (not is-done) (not has-passed))
            ;; If it hasn't passed and hasn't been clocked, don't score it yet
            (when (= clocked 0)
              (setq should-score nil))))

        (when should-score
          (setq total-effort (+ total-effort effort))
          (unless (gethash category cat-stats)
            (puthash category (list 0.0 0.0) cat-stats))
          (let ((cat-data (gethash category cat-stats)))
            (setcar cat-data (+ (car cat-data) effort)))

          (let ((task-val 1.0)
                (overlap-mins 0.0)
                (punctual-mult 1.0))
            (if marker
                (progn
                  ;; Get task score for priority weighting
                  (let ((score-info (org-auto-scheduler-calculate-score marker)))
                    (setq task-val (max 1.0 (car score-info))))

                  ;; Calculate overlap and punctuality from clock intervals
                  (when scheduled-time
                    (let* ((plan-start (org-time-string-to-time scheduled-time))
                           (plan-end (time-add plan-start (seconds-to-time (* effort 60))))
                           (first-start nil))
                      (dolist (interval clock-intervals)
                        (when (equal (nth 1 interval) id)
                          (let* ((actual-start (nth 2 interval))
                                 (actual-end (nth 3 interval)))
                            ;; Track earliest start
                            (unless first-start (setq first-start actual-start))
                            ;; Add overlap — compute the intersection of [plan-start,plan-end] and [actual-start,actual-end]
                            (let* ((overlap-start (max (float-time plan-start) (float-time actual-start)))
                                   (overlap-end (min (float-time plan-end) (float-time actual-end)))
                                   (overlap-duration (max 0.0 (- overlap-end overlap-start))))
                              (when (> overlap-duration 0)
                                (cl-incf overlap-mins (/ overlap-duration 60.0)))))))
                      ;; Calculate punctuality multiplier
                      (when first-start
                        (let ((variance-mins (/ (abs (float-time (time-subtract first-start plan-start))) 60.0)))
                          (if (<= variance-mins 15.0)
                              (setq punctual-mult 1.0)
                            ;; Lose 0.1 for every 30 mins late/early past 15 min buffer
                            (setq punctual-mult (max 0.5 (- 1.0 (* (ffloor (/ (- variance-mins 15.0) 30.0)) 0.1)))))))))

                  ;; Check if it was rescheduled
                  (let* ((current-scheduled (org-with-point-at marker (org-entry-get marker "SCHEDULED"))))
                    (when (and current-scheduled scheduled-time
                               (not (string= current-scheduled scheduled-time))
                               (not is-done))
                      (push (list heading scheduled-time current-scheduled) missed-tasks)))
                  (if is-done
                      (setq earned (float effort))
                    ;; Partial credit: up to the estimated effort
                    (setq earned (min (float effort) (float clocked)))))
              ;; Marker not found - count as 0 earned
              (setq earned 0.0))

            ;; Update multi-score totals
            (setq earned-effort (+ earned-effort earned))
            (setq total-overlap-mins (+ total-overlap-mins (min (float effort) overlap-mins)))
            (setq punctuality-earned (+ punctuality-earned (* earned punctual-mult)))
            (setq weighted-earned (+ weighted-earned (* earned task-val)))
            (setq weighted-total (+ weighted-total (* effort task-val)))

            (let ((cat-data (gethash category cat-stats)))
              (setcar (cdr cat-data) (+ (cadr cat-data) earned))))

          ;; Postponement Check (was it in yesterday's snapshot?)
          (let ((was-yesterday (cl-find-if (lambda (yt) (equal (plist-get yt :id) id)) yesterday-snapshot)))
            (when (and was-yesterday (not is-done))
              (cl-incf postponed-tasks)))

          ;; Track Missed Tasks for Time of Day Analysis
          ;; Only add if not already recorded as a rescheduled task (3-element list)
          (let ((already-rescheduled (cl-find-if (lambda (m) (and (= (length m) 3) (string= (nth 0 m) heading))) missed-tasks)))
            (when (and (not is-done) (not already-rescheduled) (< (/ earned effort) 0.8) has-passed)
              (push (list heading scheduled-time clocked effort category) missed-tasks)))

          (push (list heading earned effort is-done) tasks-results))))

    ;; 2. Unplanned Tasks Check - collect detailed info
    (org-map-entries
     (lambda ()
       (when (member (org-get-todo-state) org-done-keywords)
         (let* ((id (org-id-get))
                (in-snapshot (cl-find-if (lambda (t-snap) (equal (plist-get t-snap :id) id)) snapshot)))
           (unless in-snapshot
             (let ((closed-ts (org-entry-get (point) "CLOSED")))
               (when (and closed-ts (string= (substring closed-ts 1 11) score-date))
                 (let* ((heading (org-get-heading t t t t))
                        (effort (or (org-auto-scheduler-get-effort (point-marker)) 0))
                        (clocked (org-auto-scheduler-get-clocked-time (point-marker)))
                        (category (or (org-get-category) "Uncategorized")))
                   (push (list heading id effort clocked category) unplanned-tasks))))))))
     nil 'agenda)

    (let* ((score (if (> total-effort 0) (* (/ earned-effort total-effort) 100.0) 100.0))
           (true-adherence (if (> total-effort 0) (* (/ total-overlap-mins total-effort) 100.0) 100.0))
           (punctuality-score (if (> total-effort 0) (* (/ punctuality-earned total-effort) 100.0) 100.0))
           (weighted-score (if (> weighted-total 0) (* (/ weighted-earned weighted-total) 100.0) 100.0))
           (score-data (list :score score
                             :true-adherence true-adherence
                             :punctuality-score punctuality-score
                             :weighted-score weighted-score
                             :total-effort total-effort
                             :earned-effort earned-effort
                             :postponed postponed-tasks
                             :unplanned (length unplanned-tasks)
                             :unplanned-tasks unplanned-tasks
                             :categories cat-stats
                             :missed missed-tasks))
           (history-entry (assoc score-date org-auto-scheduler--adherence-history)))

      ;; Update History
      (if history-entry
          (setcdr history-entry score-data)
        (push (cons score-date score-data) org-auto-scheduler--adherence-history))

      (org-auto-scheduler-save-adherence)
      (unless no-display
        (with-current-buffer (get-buffer-create "*Org Auto Scheduler Scores*")
          (let ((inhibit-read-only t))
            (erase-buffer))
          (org-auto-scheduler-report-mode)
          (let ((inhibit-read-only t))
            (insert (propertize (format " Daily Schedule Adherence - %s \n" score-date) 'face 'org-document-title))
            (insert (make-string 50 ?=) "\n\n")

            ;; 1. Global Score Overview
            (let* ((streak (org-auto-scheduler-get-adherence-streak))
                   (get-color (lambda (s) (cond ((>= s 90) "green")
                                                ((>= s 70) "orange")
                                                (t "red")))))
              (insert (format "Pure Effort:       %s\n"
                              (propertize (format "%5.1f%%" score) 'face `(:foreground ,(funcall get-color score) :weight bold))))
              (insert (format "True Adherence:    %s\n"
                              (propertize (format "%5.1f%%" true-adherence) 'face `(:foreground ,(funcall get-color true-adherence) :weight bold))))
              (insert (format "Punctuality Score: %s\n"
                              (propertize (format "%5.1f%%" punctuality-score) 'face `(:foreground ,(funcall get-color punctuality-score) :weight bold))))
              (insert (format "Weighted Effort:   %s\n\n"
                              (propertize (format "%5.1f%%" weighted-score) 'face `(:foreground ,(funcall get-color weighted-score) :weight bold))))

              (insert (format "Current Streak: %d days 🔥\n" streak))
              (insert (format "Effort: %.1fh planned, %.1fh earned\n\n"
                              (/ total-effort 60.0)
                              (/ earned-effort 60.0))))

            ;; 2. Category Breakdown
            (insert (propertize " Category Breakdown \n" 'face 'org-level-1))
            (insert (make-string 30 ?-) "\n")
            (if (and cat-stats (> (hash-table-count cat-stats) 0))
                (maphash (lambda (cat stats)
                           (let* ((total (car stats))
                                  (earned (cadr stats))
                                  (cat-score (if (> total 0) (* (/ earned total) 100.0) 100.0)))
                             (insert (format "%-15s : %6.1f%% (Planned: %.1fh, Earned: %.1fh)\n"
                                             cat cat-score (/ total 60.0) (/ earned 60.0)))))
                         cat-stats)
              (insert "No categories tracked.\n"))
            (insert "\n")

            ;; 4. Time of Day Analysis / Missed Tasks
            (when missed-tasks
              (insert (propertize " Missed or Rescheduled Tasks \n" 'face 'org-level-1))
              (insert (make-string 30 ?-) "\n")
              (dolist (m missed-tasks)
                (if (= (length m) 3)
                    ;; It's a rescheduled task - find ID from snapshot
                    (let* ((heading (nth 0 m))
                           (old (nth 1 m))
                           (new (nth 2 m))
                           (snap-task (cl-find-if (lambda (s) (string= (plist-get s :heading) heading)) snapshot))
                           (task-id (and snap-task (plist-get snap-task :id))))
                      (insert "[Rescheduled] ")
                      (if task-id
                          (org-auto-scheduler--insert-linked-heading heading task-id)
                        (insert heading))
                      (insert (format "\n  From: %s\n  To:   %s\n" old new)))
                  ;; It's a standard missed task
                  (let* ((heading (nth 0 m))
                         (time (nth 1 m))
                         (clocked (nth 2 m))
                         (effort (nth 3 m))
                         (cat (nth 4 m))
                         (snap-task (cl-find-if (lambda (s) (string= (plist-get s :heading) heading)) snapshot))
                         (task-id (and snap-task (plist-get snap-task :id))))
                    (let ((time-str (if (and time (string-match "\\([0-9]\\{2\\}:[0-9]\\{2\\}\\)" time))
                                        (match-string 1 time)
                                      "Unscheduled")))
                      (insert (format "[%-5s] " time-str))
                      (if task-id
                          (org-auto-scheduler--insert-linked-heading heading task-id)
                        (insert heading))
                      (insert (format " | Effort: %dm, Clocked: %dm\n" effort clocked))))))
              (insert "\n"))

            ;; 5. Postponed & Unplanned Warnings
            (when (or (> postponed-tasks 0) (> (length unplanned-tasks) 0))
              (insert (propertize " Warnings \n" 'face 'org-level-1))
              (insert (make-string 30 ?-) "\n")
              (when (> postponed-tasks 0)
                (insert (format "⚠️ You have %d tasks that rolled over from yesterday.\n" postponed-tasks)))
              (when (> (length unplanned-tasks) 0)
                (insert (format "⚠️ The \"Squirrel!\" Penalty: You completed %d unplanned tasks today:\n" (length unplanned-tasks)))
                (dolist (ut unplanned-tasks)
                  (let ((heading (nth 0 ut))
                        (task-id (nth 1 ut))
                        (effort (nth 2 ut))
                        (clocked (nth 3 ut))
                        (category (nth 4 ut)))
                    (insert "  • ")
                    (if task-id
                        (org-auto-scheduler--insert-linked-heading heading task-id)
                      (insert heading))
                    (insert (format " [%s] Clocked: %dm\n" category clocked)))))
              (insert "\n"))

            ;; 6. Hall of Fame (Past Bests)
            (let ((best-week 0.0) (best-week-date "")
                  (best-month 0.0) (best-month-date "")
                  (best-year 0.0) (best-year-date ""))
              (dolist (entry org-auto-scheduler--adherence-history)
                (let* ((d-str (car entry))
                       (entry-data (cdr entry))
                       (entry-score (plist-get entry-data :score))
                       (entry-time (org-auto-scheduler-parse-time-string (concat d-str " 12:00")))
                       (days-ago (and entry-time (time-to-days (time-subtract current-time entry-time)))))
                  (when days-ago
                    ;; Week
                    (when (and (<= days-ago 7) (> entry-score best-week))
                      (setq best-week entry-score)
                      (setq best-week-date d-str))
                    ;; Month
                    (when (and (<= days-ago 30) (> entry-score best-month))
                      (setq best-month entry-score)
                      (setq best-month-date d-str))
                    ;; Year
                    (when (and (<= days-ago 365) (> entry-score best-year))
                      (setq best-year entry-score)
                      (setq best-year-date d-str)))))
              (when (> best-week 0)
                (insert (propertize " 🏆 Hall of Fame (Past Bests) \n" 'face 'org-level-1))
                (insert (make-string 30 ?-) "\n")
                (insert (format "Best Last 7 Days:  %6.1f%% (%s)\n" best-week best-week-date))
                (insert (format "Best Last 30 Days: %6.1f%% (%s)\n" best-month best-month-date))
                (insert (format "Best Last 1 Year:  %6.1f%% (%s)\n" best-year best-year-date))
                (insert "\n")))

            ;; 7. Historical Multipliers
            (when org-auto-scheduler-historical-multipliers
              (insert (propertize " Estimation vs Reality (Historical Multipliers) \n" 'face 'org-level-1))
              (insert (make-string 30 ?-) "\n")
              (dolist (m org-auto-scheduler-historical-multipliers)
                (insert (format "%-15s : %5.2fx (meaning tasks take %s time than estimated)\n"
                                (car m) (cdr m)
                                (if (> (cdr m) 1.2) "more" (if (< (cdr m) 0.8) "less" "about the same"))))))

            ;; 7. Compact Gantt Timeline
            (when snapshot
              (org-auto-scheduler--render-compact-gantt score-date snapshot))

            ;; 8. 30-Day Trend (2x2 Grid at bottom)
            (insert (propertize " 📈 30-Day Trend \n" 'face 'org-level-1))
            (insert (make-string 30 ?-) "\n")

            (let ((graph1 (org-auto-scheduler--get-bar-graph-lines "Pure Effort" :score score-date))
                  (graph2 (org-auto-scheduler--get-bar-graph-lines "True Adherence" :true-adherence score-date))
                  (graph3 (org-auto-scheduler--get-bar-graph-lines "Punctuality" :punctuality-score score-date))
                  (graph4 (org-auto-scheduler--get-bar-graph-lines "Weighted Score" :weighted-score score-date)))
              ;; Top row (Effort, Adherence)
              (dotimes (i 14)
                (insert (nth i graph1) "  " (nth i graph2) "\n"))
              (insert "\n")
              ;; Bottom row (Punctuality, Weighted)
              (dotimes (i 14)
                (insert (nth i graph3) "  " (nth i graph4) "\n")))

            (goto-char (point-min)))
          (display-buffer (current-buffer))))
      (message "Schedule scored: %.1f%% adherence calculated for %s." score score-date))))

;;;###autoload
(defun org-auto-scheduler-adherence-report (&optional date-str)
  "Display the full adherence report buffer for DATE-STR (defaults to today).
Calculates schedule adherence against the morning snapshot and displays the
adherence report buffer."
  (interactive
   (list (when current-prefix-arg
           (let ((prompt-date (org-read-date nil nil nil "Adherence report for date: ")))
             (when prompt-date
               (format-time-string "%Y-%m-%d" (org-time-string-to-time prompt-date)))))))
  (org-auto-scheduler-score-schedule date-str))

(defun org-auto-scheduler-get-adherence-streak ()
  "Calculate current adherence streak (> 80% score)."
  (let ((streak 0)
        (date (current-time)))
    (catch 'break
      (while t
        (let* ((date-str (format-time-string "%Y-%m-%d" date))
               (entry (assoc date-str org-auto-scheduler--adherence-history)))
          (if entry
              (let ((score (plist-get (cdr entry) :score)))
                (if (>= score 80.0)
                    (cl-incf streak)
                  (throw 'break t)))
            (throw 'break t)))
        (setq date (time-subtract date (days-to-time 1)))))
    streak))

;;; Weekly Retrospective Mode

(defvar org-auto-scheduler-retrospective-mode-map
  (let ((map (make-sparse-keymap)))
    (set-keymap-parent map special-mode-map)
    (define-key map (kbd "q") #'quit-window)
    (define-key map (kbd "RET") #'org-auto-scheduler-report-jump-to-task)
    (define-key map (kbd "TAB") #'org-auto-scheduler-report-jump-to-task)
    map)
  "Keymap for `org-auto-scheduler-retrospective-mode'.")

(define-derived-mode org-auto-scheduler-retrospective-mode special-mode "AutoSch-Retro"
  "Major mode for viewing the weekly schedule retrospective report."
  (setq buffer-read-only t))

(defun org-auto-scheduler--analyze-retrospective (&optional num-days)
  "Analyze execution metrics across `org-agenda-files` over the past NUM-DAYS (default 7)."
  (let* ((days (or num-days 7))
         (now (current-time))
         (start-time (time-subtract now (seconds-to-time (* days 86400))))
         (end-of-today (org-auto-scheduler-time-with-time-string now "23:59"))
         (start-date-str (format-time-string "%Y-%m-%d" start-time))
         (end-date-str (format-time-string "%Y-%m-%d" now))
         (done-count 0)
         (planned-count 0)
         (rolled-count 0)
         (planned-effort-mins 0)
         (planned-clocked-mins 0)
         (unplanned-clocked-mins 0)
         (project-stats (make-hash-table :test 'equal)))
    (dolist (file (org-agenda-files t))
      (when (and file (file-exists-p file))
        (with-current-buffer (find-file-noselect file)
          (org-map-entries
           (lambda ()
             (let* ((m (point-marker))
                    (state (org-get-todo-state))
                    (is-done (and state (member state (or org-done-keywords '("DONE")))))
                    (tags (org-get-tags))
                    (is-autosch (member "AUTOSCH" tags))
                    (effort (or (org-auto-scheduler-get-effort m) 0))
                    (clocked (org-auto-scheduler-get-clocked-time m))
                    (proj (or (org-auto-scheduler-get-project-id m) "Uncategorized"))
                    (closed (org-entry-get nil "CLOSED"))
                    (closed-time (when closed (org-time-string-to-time closed)))
                    (sched (org-entry-get nil "SCHEDULED"))
                    (sched-time (when sched (org-time-string-to-time sched))))
               (when (or (and closed-time (not (time-less-p closed-time start-time)) (not (time-less-p end-of-today closed-time)))
                         (and sched-time (not (time-less-p sched-time start-time)) (not (time-less-p end-of-today sched-time)))
                         (> clocked 0))
                 (if is-autosch
                     (progn
                       (cl-incf planned-count)
                       (cl-incf planned-effort-mins effort)
                       (cl-incf planned-clocked-mins clocked)
                       (if is-done
                           (cl-incf done-count)
                         (cl-incf rolled-count)))
                   (when (> clocked 0)
                     (cl-incf unplanned-clocked-mins clocked)))
                 (when (or (> clocked 0) is-autosch is-done)
                   (let ((p-data (gethash proj project-stats (list :done 0 :total 0 :clocked 0))))
                     (when is-done (setf (plist-get p-data :done) (1+ (plist-get p-data :done))))
                     (setf (plist-get p-data :total) (1+ (plist-get p-data :total)))
                     (setf (plist-get p-data :clocked) (+ (plist-get p-data :clocked) clocked))
                     (puthash proj p-data project-stats))))))
           nil 'file))))
    (list :days days
          :start-date start-date-str
          :end-date end-date-str
          :done done-count
          :planned planned-count
          :rolled rolled-count
          :planned-effort planned-effort-mins
          :planned-clocked planned-clocked-mins
          :unplanned-clocked unplanned-clocked-mins
          :projects project-stats)))

(defun org-auto-scheduler-weekly-retrospective (&optional num-days)
  "Display the weekly retrospective summary buffer analyzing execution over the past NUM-DAYS (default 7)."
  (interactive "P")
  (let* ((days (if (and num-days (numberp num-days)) num-days 7))
         (metrics (org-auto-scheduler--analyze-retrospective days))
         (retro-buf (get-buffer-create "*Org Auto Scheduler Retrospective*"))
         (start-date (plist-get metrics :start-date))
         (end-date (plist-get metrics :end-date))
         (done (plist-get metrics :done))
         (planned (plist-get metrics :planned))
         (rolled (plist-get metrics :rolled))
         (completion-pct (if (> planned 0) (/ (* done 100.0) planned) 0.0))
         (planned-effort-h (/ (plist-get metrics :planned-effort) 60.0))
         (planned-clocked-h (/ (plist-get metrics :planned-clocked) 60.0))
         (unplanned-clocked-h (/ (plist-get metrics :unplanned-clocked) 60.0))
         (total-clocked-h (+ planned-clocked-h unplanned-clocked-h))
         (accuracy-ratio (if (> planned-effort-h 0) (/ planned-clocked-h planned-effort-h) 1.0))
         (focus-pct (if (> total-clocked-h 0) (/ (* planned-clocked-h 100.0) total-clocked-h) 100.0))
         (unplanned-pct (- 100.0 focus-pct))
         (projects (plist-get metrics :projects)))
    (with-current-buffer retro-buf
      (let ((inhibit-read-only t))
        (erase-buffer)
        (org-auto-scheduler-retrospective-mode)
        (insert "================================================================================
")
        (insert (format " Org Auto Scheduler: Weekly Retrospective (%s to %s)
" start-date end-date))
        (insert "================================================================================

")

        (insert (propertize "🎯 Execution & Completion Rates:
" 'face 'bold))
        (insert (format "   • Tasks Scheduled:  %d
" planned))
        (insert (format "   • Tasks Completed:  %d (%.1f%%)
" done completion-pct))
        (insert (format "   • Tasks Rolled:     %d

" rolled))

        (insert (propertize "⏱ Focus Time & Estimation Accuracy:
" 'face 'bold))
        (insert (format "   • Planned Effort:   %.1fh
" planned-effort-h))
        (insert (format "   • Actual Clocked:   %.1fh
" planned-clocked-h))
        (insert (format "   • Accuracy Ratio:   %.2fx (%s)

"
                        accuracy-ratio
                        (cond
                         ((> accuracy-ratio 1.15) (format "Tasks took ~%d%% longer than estimated" (round (* (- accuracy-ratio 1.0) 100))))
                         ((< accuracy-ratio 0.85) (format "Tasks finished ~%d%% faster than estimated" (round (* (- 1.0 accuracy-ratio) 100))))
                         (t "Close to estimated effort"))))

        (insert (propertize "🐿 Planned Focus vs Unplanned Work (\"Squirrel\" Factor):
" 'face 'bold))
        (insert (format "   • Planned Focus:    %.1fh (%.1f%%)
" planned-clocked-h focus-pct))
        (insert (format "   • Unplanned Work:   %.1fh (%.1f%%)

" unplanned-clocked-h unplanned-pct))

        (insert (propertize "📊 Project & Category Breakdown:
" 'face 'bold))
        (insert "   ┌──────────────────────────────┬───────────┬────────────┬─────────────┐
")
        (insert "   │ Project / Category           │ Completed │ Clocked    │ Completion  │
")
        (insert "   ├──────────────────────────────┼───────────┼────────────┼─────────────┤
")
        (maphash (lambda (name p-data)
                   (let* ((p-done (plist-get p-data :done))
                          (p-total (plist-get p-data :total))
                          (p-clocked-h (/ (plist-get p-data :clocked) 60.0))
                          (p-pct (if (> p-total 0) (/ (* p-done 100.0) p-total) 0.0)))
                     (insert (format "   │ %-28s │ %4d/%-4d │ %8.1fh │ %10.1f%% │
"
                                     (truncate-string-to-width name 28 nil nil "…")
                                     p-done p-total p-clocked-h p-pct))))
                 projects)
        (insert "   └──────────────────────────────┴───────────┴────────────┴─────────────┘

")
        (insert " Keys: [q] Close retrospective buffer
"))
      (goto-char (point-min)))
    (display-buffer retro-buf)))

;;; Adherence Report Mode (TAB / RET jump-to-task)

(defvar org-auto-scheduler-report-mode-map
  (let ((map (make-sparse-keymap)))
    (set-keymap-parent map special-mode-map)
    (define-key map (kbd "TAB") #'org-auto-scheduler-report-jump-to-task)
    (define-key map (kbd "RET") #'org-auto-scheduler-report-jump-to-task)
    map)
  "Keymap for `org-auto-scheduler-report-mode`.")

(define-derived-mode org-auto-scheduler-report-mode special-mode "AutoSch-Report"
  "Major mode for viewing the adherence report with TAB/RET jump-to-task.")

(defun org-auto-scheduler-report-jump-to-task ()
  "Jump to the Org task under point using the `org-id` text property."
  (interactive)
  (let ((task-id (get-text-property (point) 'org-id)))
    (if task-id
        (let ((marker (org-id-find task-id t)))
          (if marker
              (progn
                (switch-to-buffer-other-window (marker-buffer marker))
                (goto-char marker)
                (org-show-context))
            (user-error "Cannot find task with ID %s" task-id)))
      (user-error "No task link at point"))))

(defun org-auto-scheduler--insert-linked-heading (heading task-id)
  "Insert HEADING with an `org-id` text property set to TASK-ID.
This enables TAB/RET navigation from the report buffer."
  (let ((start (point)))
    (insert (propertize heading
                        'org-id task-id
                        'face 'link
                        'mouse-face 'highlight))))

;;; Clock interval extraction for timeline

(defun org-auto-scheduler-get-clock-intervals (date-str)
  "Return a list of (HEADING ID START-TIME END-TIME) for all CLOCK entries on DATE-STR.
Scans all org-agenda-files for CLOCK lines matching the target date."
  (let ((intervals nil))
    (dolist (file (org-agenda-files))
      (with-current-buffer (find-file-noselect file)
        (org-with-wide-buffer
         (goto-char (point-min))
         (while (re-search-forward
                 "^[ \t]*CLOCK: \\[\\([^]]+\\)\\]--\\[\\([^]]+\\)\\]" nil t)
           (let* ((start-str (match-string 1))
                  (end-str (match-string 2))
                  (start-time (org-auto-scheduler-parse-time-string start-str))
                  (end-time (org-auto-scheduler-parse-time-string end-str))
                  (start-date (format-time-string "%Y-%m-%d" start-time)))
             (when (string= start-date date-str)
               (save-excursion
                 (org-back-to-heading t)
                 (let ((heading (org-get-heading t t t t))
                       (id (org-id-get)))
                   (push (list heading id start-time end-time) intervals)))))))))
    (sort intervals (lambda (a b) (time-less-p (nth 2 a) (nth 2 b))))))

;;; Compact Gantt Timeline Rendering

(defun org-auto-scheduler--time-to-day-minutes (time-val)
  "Convert TIME-VAL to minutes since midnight of that day."
  (let* ((decoded (decode-time time-val))
         (hour (nth 2 decoded))
         (minute (nth 1 decoded)))
    (+ (* hour 60) minute)))

(defun org-auto-scheduler--render-gantt-row (label intervals chunk-start-min chunk-end-min chars-per-min date-str legend-hash)
  "Render a single Gantt row for LABEL (e.g. \"Planned\", \"Actual\").
INTERVALS is a list of (HEADING ID START-TIME END-TIME).
CHUNK-START-MIN and CHUNK-END-MIN are minute offsets from midnight.
CHARS-PER-MIN is the character resolution (e.g. 0.2 = 1 char per 5 min).
DATE-STR is the target date for clamping.
LEGEND-HASH maps task IDs to short numbers strings for display."
  (let* ((chunk-width (round (* (- chunk-end-min chunk-start-min) chars-per-min)))
         (row (make-string chunk-width ?\s)))
    ;; Fill in each interval
    (dolist (interval intervals)
      (let* ((start-min (org-auto-scheduler--time-to-day-minutes (nth 2 interval)))
             (end-min (org-auto-scheduler--time-to-day-minutes (nth 3 interval)))
             ;; Clamp to chunk boundaries
             (clamped-start (max start-min chunk-start-min))
             (clamped-end (min end-min chunk-end-min))
             (heading (nth 0 interval))
             (id (nth 1 interval)))
        (when (> clamped-end clamped-start)
          (let* ((col-start (round (* (- clamped-start chunk-start-min) chars-per-min)))
                 (col-end (round (* (- clamped-end chunk-start-min) chars-per-min)))
                 (safe-start (max 0 (min col-start (1- chunk-width))))
                 (safe-end (max (1+ safe-start) (min col-end chunk-width)))
                 (block-len (- safe-end safe-start))
                 (legend-val (if id (gethash id legend-hash (list heading nil)) (list heading nil)))
                 (legend-id (if (stringp legend-val) legend-val (car legend-val)))
                 (block-color (if (stringp legend-val) nil (cadr legend-val)))
                 ;; Truncate heading to fit
                 (display-name (if (> (length legend-id) (- block-len 2))
                                   (if (> block-len 4)
                                       (concat (substring legend-id 0 (- block-len 3)) "..")
                                     (make-string block-len ?=))
                                 legend-id))
                 ;; Pad name within block
                 (pad-len (max 0 (- block-len (length display-name) 2)))
                 (pad-left (/ pad-len 2))
                 (pad-right (- pad-len pad-left))
                 (raw-padded (concat "[" (make-string pad-left ?=) display-name (make-string pad-right ?=) "]"))
                 (padded (if block-color (propertize raw-padded 'face `(:foreground ,block-color)) raw-padded)))
            ;; Continuation markers for tasks spanning chunk boundaries
            (when (< start-min chunk-start-min)
              (aset row safe-start ?<))
            (when (> end-min chunk-end-min)
              (when (< (1- safe-end) chunk-width)
                (aset row (1- safe-end) ?>)))
            ;; Write the block into the row
            (let ((write-str (substring raw-padded 0 (min (length raw-padded) block-len))))
              (dotimes (i (min (length write-str) (- chunk-width safe-start)))
                (let ((char (aref write-str i)))
                  ;; If it's a visible char, inject it with properties directly if colored
                  (if block-color
                      (put-text-property (+ safe-start i) (+ safe-start i 1)
                                         'face block-color row))
                  (aset row (+ safe-start i) char))))))))
    (insert (format "%-8s %s\n" label row))))

(defun org-auto-scheduler--render-timeline-header (chunk-start-min chunk-end-min chars-per-min)
  "Insert a timeline header with hour markers.
CHUNK-START-MIN and CHUNK-END-MIN are minute offsets from midnight."
  (let* ((chunk-width (round (* (- chunk-end-min chunk-start-min) chars-per-min)))
         (header (make-string chunk-width ?\s))
         (ruler (make-string chunk-width ?\s)))
    ;; Place hour labels and tick marks
    (let ((hour-start (/ chunk-start-min 60)))
      (cl-loop for hour from hour-start to (/ chunk-end-min 60)
               for col = (round (* (- (* hour 60) chunk-start-min) chars-per-min))
               when (and (>= col 0) (< col chunk-width))
               do (let ((label (format "%02d:00" hour)))
                    ;; Write hour label into header
                    (dotimes (i (min (length label) (- chunk-width col)))
                      (aset header (+ col i) (aref label i)))
                    ;; Write tick mark into ruler
                    (aset ruler col ?|))))
    (insert (format "%-8s %s\n" "" header))
    (insert (format "%-8s %s\n" "" ruler))))

(defun org-auto-scheduler--render-compact-gantt (date-str snapshot)
  "Render the compact chunked Gantt timeline for DATE-STR.
SNAPSHOT is the planned schedule snapshot for the day.
Clocked intervals are extracted from the org files."
  (let* ((chunk-hours 4)        ;; 4-hour chunks
         (chars-per-min (/ 1.0 5))  ;; 1 char per 5 minutes => 12 chars/hour
         ;; Parse start/end times from the customization
         (start-minutes (org-duration-to-minutes org-auto-scheduler-start-time))
         (end-minutes (org-duration-to-minutes org-auto-scheduler-end-time))
         ;; Build planned intervals from snapshot
         (planned-intervals nil)
         ;; Get actual clocked intervals
         (clocked-intervals (org-auto-scheduler-get-clock-intervals date-str))
         (date-time (org-auto-scheduler-parse-time-string (concat date-str " 00:00")))
         (legend-hash (make-hash-table :test 'equal))
         (legend-list nil)
         (legend-counter 1)
         (colors '(font-lock-keyword-face
                   font-lock-type-face
                   font-lock-string-face
                   font-lock-variable-name-face
                   font-lock-function-name-face
                   font-lock-constant-face
                   font-lock-builtin-face
                   font-lock-warning-face))
         (color-idx 0))
    ;; Build planned intervals from snapshot
    (dolist (task snapshot)
      (let* ((heading (plist-get task :heading))
             (id (plist-get task :id))
             (effort (or (plist-get task :effort) 30))
             (scheduled-str (plist-get task :scheduled))
             (scheduled-time (when scheduled-str (org-time-string-to-time scheduled-str)))
             (scheduled-date (when scheduled-time (format-time-string "%Y-%m-%d" scheduled-time))))
        (when (and scheduled-time (string= scheduled-date date-str))
          (let ((end-time (time-add scheduled-time (seconds-to-time (* effort 60)))))
            (push (list heading id scheduled-time end-time) planned-intervals)))))
    (setq planned-intervals (sort planned-intervals (lambda (a b) (time-less-p (nth 2 a) (nth 2 b)))))

    ;; Build legend hash before rendering with colors
    (dolist (interval (append planned-intervals clocked-intervals))
      (let ((heading (nth 0 interval))
            (id (nth 1 interval)))
        (when (and id (not (gethash id legend-hash)))
          (let* ((legend-id (number-to-string legend-counter))
                 (assigned-color (nth (% color-idx (length colors)) colors)))
            (puthash id (list legend-id assigned-color) legend-hash)
            (push (list legend-id heading id assigned-color) legend-list)
            (cl-incf legend-counter)
            (cl-incf color-idx)))))
    (setq legend-list (nreverse legend-list))

    (insert (propertize " 📊 Daily Timeline \n" 'face 'org-level-1))
    (insert (make-string 30 ?-) "\n")
    (when (and (null planned-intervals) (null clocked-intervals))
      (insert "No timeline data available.\n\n")
      (cl-return-from org-auto-scheduler--render-compact-gantt nil))

    ;; Render chunk by chunk (Explicitly 06:00 - 12:00, 12:00 - 18:00, 18:00 - 24:00)
    (let ((chunks '((360 720) (720 1080) (1080 1440))))
      (dolist (chunk chunks)
        (let ((chunk-start (car chunk))
              (chunk-end (cadr chunk)))
          ;; Header with hour markers
          (org-auto-scheduler--render-timeline-header chunk-start chunk-end chars-per-min)
          ;; Planned row
          (org-auto-scheduler--render-gantt-row "Planned" planned-intervals chunk-start chunk-end chars-per-min date-str legend-hash)
          ;; Actual row
          (org-auto-scheduler--render-gantt-row "Actual" clocked-intervals chunk-start chunk-end chars-per-min date-str legend-hash)
          (insert "\n"))))
    (insert "\n")
    ;; Render Legend
    (when legend-list
      (insert (propertize " Timeline Legend \n" 'face 'org-level-2))
      (insert (make-string 30 ?-) "\n")
      (dolist (item legend-list)
        (let* ((legend-id (nth 0 item))
               (heading (nth 1 item))
               (id (nth 2 item))
               (color (nth 3 item))
               ;; Since color is a face symbol (e.g., 'font-lock-keyword-face), we use it directly
               (fmt-legend-id (if color (propertize (format " [%2s] " legend-id) 'face color)
                                (format " [%2s] " legend-id))))
          (insert fmt-legend-id)
          (if id
              (let ((start (point)))
                (insert (propertize heading
                                    'org-id id
                                    'face (if color `(:inherit ,color :underline t) 'link)
                                    'mouse-face 'highlight)))
            (insert (if color (propertize heading 'face color) heading)))
          (insert "\n")))
      (insert "\n"))))

;;; Adherence Report

(defun org-auto-scheduler--get-bar-graph-lines (label property target-date-str)
  "Return a list of strings representing a 10-row high bar graph for LABEL.
Extracts PROPERTY from history ending at TARGET-DATE-STR.
Normalizes the Y-axis based on the maximum score in the 30-day window."
  (let* ((days 30)
         (target-time (org-auto-scheduler-parse-time-string (concat target-date-str " 12:00")))
         (values nil)
         ;; Unicode blocks:   ▂ ▃ ▄ ▅ ▆ ▇ █ (8 levels, plus space for 0)
         (bars [" " " " "▂" "▃" "▄" "▅" "▆" "▇" "█"])
         (latest-val 0.0)
         (lines nil))
    ;; Collect last 30 days of data
    (dotimes (i days)
      (let* ((date-time (time-subtract target-time (days-to-time (- (1- days) i))))
             (date-str (format-time-string "%Y-%m-%d" date-time))
             (entry (assoc date-str org-auto-scheduler--adherence-history))
             (val (if entry (or (plist-get (cdr entry) property) (plist-get (cdr entry) :score) 0.0) 0.0)))
        (push val values)
        (when (= i (1- days))
          (setq latest-val val))))
    (setq values (nreverse values))

    ;; Build output array
    (let* ((color (cond ((>= latest-val 90) "green")
                        ((>= latest-val 70) "orange")
                        (t "red")))
           (actual-max (apply #'max values))
           (max-val (max 10.0 (* 10.0 (ceiling (/ actual-max 10.0)))))
           (rows 10))

      ;; Header lines
      (push (format "%-25s (Last 30 Days)" label) lines)
      (push (make-string 38 ?-) lines)

      ;; Graph lines
      (dotimes (r rows)
        (let* ((level (- rows r))
               (threshold (* (/ max-val rows) level))
               (prev-threshold (* (/ max-val rows) (1- level)))
               (y-label (format "%4s | " (format "%d%%" (round threshold))))
               (row-str y-label))
          ;; Build the row string horizontally
          (dolist (val values)
            (let ((char (cond ((>= val threshold) "█")
                              ((and (< val threshold) (> val prev-threshold))
                               (let* ((fraction (/ (float (- val prev-threshold)) (float (- threshold prev-threshold))))
                                      (idx (max 0 (min 8 (round (* fraction 8))))))
                                 (aref bars idx)))
                              (t " "))))
              (setq row-str (concat row-str (propertize char 'face `(:foreground ,color))))))
          (push row-str lines)))

      ;; X-axis
      (push (concat "       +" (make-string days ?-)) lines)
      (push " " lines))

    (nreverse lines)))

(defun org-auto-scheduler-adherence-generate ()
  "Recalculate adherence scores silently for all available snapshot dates."
  (interactive)
  (let ((count 0))
    (dolist (snap org-auto-scheduler--adherence-snapshots)
      (org-auto-scheduler-score-schedule (car snap) t)
      (cl-incf count))
    (message "Successfully regenerated adherence scores for %d days." count)))

(defvar org-auto-scheduler--adherence-timer nil
  "Timer for updating the adherence score in the mode line.")

(defvar org-auto-scheduler-adherence-string ""
  "String displayed in the global mode line representing current adherence.")

(defun org-auto-scheduler-update-adherence-score-silent ()
  "Silently update the daily adherence score in the background without displaying."
  (let* ((today-date (format-time-string "%Y-%m-%d"))
         (snapshot (cdr (assoc today-date org-auto-scheduler--adherence-snapshots)))
         (current-time (current-time))
         (total-effort 0.0)
         (earned-effort 0.0))
    (when snapshot
      (dolist (task snapshot)
        (let* ((id (plist-get task :id))
               (effort (or (plist-get task :effort) 30))
               (scheduled-time (plist-get task :scheduled))
               (marker (org-id-find id t))
               (earned 0.0)
               (should-score t)
               (is-done nil)
               (clocked 0))

          (when marker
            (org-with-point-at marker
              (setq is-done (member (org-get-todo-state) org-done-keywords))
              (setq clocked (org-auto-scheduler-get-clocked-time marker))))

          (when (and scheduled-time (not is-done))
            (let* ((scheduled-ts (org-time-string-to-time scheduled-time))
                   (has-passed (time-less-p scheduled-ts current-time)))
              (unless has-passed
                (when (= clocked 0)
                  (setq should-score nil)))))

          (when should-score
            (setq total-effort (+ total-effort effort))
            (when marker
              (if is-done
                  (setq earned (float effort))
                (setq earned (min (float effort) (float clocked)))))
            (setq earned-effort (+ earned-effort earned)))))
      (let* ((score (if (> total-effort 0) (* (/ earned-effort total-effort) 100.0) 100.0))
             (streak (org-auto-scheduler-get-adherence-streak)))
        (setq org-auto-scheduler-adherence-string
              (format " [Adh: %.0f%%%s]" score (if (> streak 0) (format " 🔥%d" streak) "")))
        (force-mode-line-update t)))))

(defun org-auto-scheduler-adherence-mode-line-enable ()
  "Enable displaying the adherence score in the global mode line."
  (interactive)
  (unless (memq 'org-auto-scheduler-adherence-string global-mode-string)
    (setq global-mode-string (append global-mode-string '(org-auto-scheduler-adherence-string))))
  (when org-auto-scheduler--adherence-timer
    (cancel-timer org-auto-scheduler--adherence-timer))
  ;; Update immediately, then every 5 minutes
  (org-auto-scheduler-update-adherence-score-silent)
  (setq org-auto-scheduler--adherence-timer
        (run-with-timer 300 300 #'org-auto-scheduler-update-adherence-score-silent))
  (message "Org Auto Scheduler adherence score enabled in mode line."))

(defun org-auto-scheduler-adherence-mode-line-disable ()
  "Disable displaying the adherence score in the global mode line."
  (interactive)
  (setq global-mode-string (delq 'org-auto-scheduler-adherence-string global-mode-string))
  (when org-auto-scheduler--adherence-timer
    (cancel-timer org-auto-scheduler--adherence-timer)
    (setq org-auto-scheduler--adherence-timer nil))
  (message "Org Auto Scheduler adherence score disabled in mode line."))

;;; Overrun Modeline Warning & Faces

(defface org-auto-scheduler-overrun-face
  '((t (:inherit font-lock-warning-face :weight bold)))
  "Face for displaying task overrun warning in the mode line."
  :group 'org-auto-scheduler)

(defvar org-auto-scheduler--overrun-string ""
  "Mode line string displaying current clocked task overrun warning.")
(put 'org-auto-scheduler--overrun-string 'risky-local-variable t)

(defvar org-auto-scheduler--overrun-timer nil
  "Timer for updating the overrun mode-line indicator.")

(defun org-auto-scheduler--update-overrun-modeline ()
  "Update `org-auto-scheduler--overrun-string' based on current clock and scheduled time."
  (if (and org-auto-scheduler-overrun-mode-line-enabled
           (fboundp 'org-clock-is-active)
           (org-clock-is-active)
           (boundp 'org-clock-marker)
           (markerp org-clock-marker)
           (marker-buffer org-clock-marker))
      (let* ((now (current-time))
             (m org-clock-marker)
             (sched-str (org-with-point-at m (org-entry-get nil "SCHEDULED")))
             (range (when sched-str (org-auto-scheduler-parse-scheduled-time-range sched-str)))
             (end-time (nth 1 range))
             (today-str (format-time-string "%Y-%m-%d" now))
             (is-today-slot (and end-time (string= (format-time-string "%Y-%m-%d" end-time) today-str)))
             (overrun-mins (when (and is-today-slot (time-less-p end-time now))
                             (round (/ (float-time (time-subtract now end-time)) 60)))))
        (if (and overrun-mins (> overrun-mins 0))
            (setq org-auto-scheduler--overrun-string
                  (propertize (format " [Overrun +%dm ⚠️]" overrun-mins)
                              'face 'org-auto-scheduler-overrun-face
                              'help-echo (format "Task is %d minutes past scheduled end. C-c a e to extend." overrun-mins)))
          (setq org-auto-scheduler--overrun-string ""))
        (force-mode-line-update t))
    (unless (string= org-auto-scheduler--overrun-string "")
      (setq org-auto-scheduler--overrun-string "")
      (force-mode-line-update t))))

(defun org-auto-scheduler-overrun-mode-line-enable ()
  "Enable displaying the task overrun indicator in the global mode line."
  (interactive)
  (unless (memq 'org-auto-scheduler--overrun-string global-mode-string)
    (setq global-mode-string (append global-mode-string '(org-auto-scheduler--overrun-string))))
  (when org-auto-scheduler--overrun-timer
    (cancel-timer org-auto-scheduler--overrun-timer))
  (org-auto-scheduler--update-overrun-modeline)
  (setq org-auto-scheduler--overrun-timer
        (run-with-timer 30 30 #'org-auto-scheduler--update-overrun-modeline))
  (message "Org Auto Scheduler task overrun mode line enabled."))

(defun org-auto-scheduler-overrun-mode-line-disable ()
  "Disable displaying the task overrun indicator in the global mode line."
  (interactive)
  (setq global-mode-string (delq 'org-auto-scheduler--overrun-string global-mode-string))
  (when org-auto-scheduler--overrun-timer
    (cancel-timer org-auto-scheduler--overrun-timer)
    (setq org-auto-scheduler--overrun-timer nil))
  (setq org-auto-scheduler--overrun-string "")
  (force-mode-line-update t)
  (message "Org Auto Scheduler task overrun mode line disabled."))

;; Auto-enable overrun mode line indicator if enabled
(when org-auto-scheduler-overrun-mode-line-enabled
  (org-auto-scheduler-overrun-mode-line-enable))

(provide 'org-auto-scheduler-analytics)

;;; org-auto-scheduler-analytics.el ends here
